version: '3'

networks:
 jenkins:

services:

  jenkins:
    container_name: jenkins
    user: root
    image: jenkins/jenkins
    networks:
      - jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /data/jenkins:/var/lib/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    environment:
      - JENKINS_HOME=/var/lib/jenkins
      - JAVA_OPTS=-Duser.timezone=Europe/Kiev
      - JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Dhudson.model.DirectoryBrowserSupport.CSP=\"default-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' 'unsafe-inline' data:;\""
    logging:
      driver: "journald"

  sonarqube:
    container_name: sonarqube
    image: sonarqube:alpine
    ports:
      - "9000:9000"
    networks:
      - jenkins
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
      - /data/sonarqube/conf:/opt/sonarqube/conf
      - /data/sonarqube/logs:/opt/sonarqube/logs
      - /data/sonarqube/temp:/opt/sonarqube/temp
      - /data/sonarqube/data:/opt/sonarqube/data
      - /data/sonarqube/extensions:/opt/sonarqube/extensions
      - /data/sonarqube/bundled_plugins:/opt/sonarqube/lib/bundled-plugins
    logging:
      driver: "journald"

  db:
    image: postgres:alpine
    container_name: db  
    networks:
      - jenkins
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar  
    volumes:
      - /data/sonarqube/postgresql:/var/lib/postgresql
      - /data/sonarqube/postgresql_data:/var/lib/postgresql/data
    logging:
      driver: "journald"

  jira:
    container_name: jira 
    image: atlassian/jira-software:latest 
    networks:
      - jenkins  
    volumes:
      - /data/jira:/var/atlassian/application-data/jira  
    environment:
     - ATL_PROXY_NAME=jira.internal
     - ATL_PROXY_PORT=80
     - ATL_TOMCAT_SCHEME=http 

  confluence: 
    container_name: confluence
    image: atlassian/confluence-server:latest
    networks:
      - jenkins  
    volumes:
      - /data/confluence-home:/var/atlassian/application-data/confluence  
    environment: 
     - ATL_PROXY_NAME=confluence.internal
     - ATL_PROXY_PORT=80
     - ATL_TOMCAT_SCHEME=http

  bitbucket: 
    container_name: bitbucket 
    image: atlassian/bitbucket-server:latest 
    networks:
      - jenkins  
    volumes:
      - /data/bitbucketVolume:/var/atlassian/application-data/bitbucket  
    environment: 
     - SERVER_PROXY_NAME=bitbucket.internal
     - SERVER_PROXY_PORT=80
     - SERVER_SCHEME=http 

  nginx: 
    container_name: nginx 
    image: nginx:alpine
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf 
    depends_on: 
     - jira 
     - confluence 
     - bitbucket 
     - jenkins
     - sonarqube  
    ports: 
     - "80:80" 
    networks: 
      jenkins: 
        aliases:
         - jira.internal
         - confluence.internal
         - bitbucket.internal 
